---
name: benchmark
on:
  push:
    branches:
      - master
    paths-ignore: [ 'README.md', 'LICENSE.txt' ]
jobs:
  benchmark:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 20
      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-jdk-${{ matrix.java }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-jdk-${{ matrix.java }}-maven-
      - run: make
      - uses: peter-evans/create-pull-request@v5
        with:
          branch: benchmark
          commit-message: 'new benchmark results'
          delete-branch: true
          title: 'New results of benchmarking'
          assignees: yegor256
          base: master