# The MIT License (MIT)
#
# Copyright (c) 2023-2025 Objectionary.com
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
---
name: make
'on':
  push:
    branches:
      - master
    paths-ignore: [ 'README.md', 'LICENSE.txt' ]
  pull_request:
    branches:
      - master
    paths-ignore: [ 'README.md', 'LICENSE.txt' ]
concurrency:
  group: make-${{ github.ref }}
  cancel-in-progress: true
jobs:
  make:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 23
      - uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ubuntu-jdk-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ubuntu-jdk-maven-
      - run: |
          set -x
          SECONDS=0
          make
          results=$(
            cat results.md
            printf "\nThe entire test took %d seconds.\n" "${SECONDS}"
          )
          export results
          perl -i -0777 -pe 's/(?<=<!-- benchmark_begin -->).*(?=<!-- benchmark_end -->)/\n$ENV{results}\n/gs;' README.md
          url=${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}
          export url
          perl -i -0777 -pe 's/(?<=\[benchmark-gha\]: ).*(?=\n)/$ENV{url}/gs;' README.md
        if: github.ref == 'refs/heads/master'
      - uses: peter-evans/create-pull-request@v7
        with:
          branch: make
          commit-message: 'new benchmark results'
          delete-branch: true
          title: 'New results of benchmarking'
          assignees: yegor256
          base: master
        if: github.ref == 'refs/heads/master'
      - run: mv html gh-pages
      - uses: JamesIves/github-pages-deploy-action@v4.7.2
        with:
          branch: gh-pages
          folder: gh-pages
          clean: false
        if: github.ref == 'refs/heads/master'
