# SPDX-FileCopyrightText: Copyright (c) 2023-2025 Objectionary.com
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: make
'on':
  push:
    branches:
      - master
    paths-ignore: ['README.md', 'LICENSE.txt']
  pull_request:
    branches:
      - master
    paths-ignore: ['README.md', 'LICENSE.txt']
concurrency:
  group: make-${{ github.ref }}
  cancel-in-progress: true
jobs:
  make:
    timeout-minutes: 45
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 23
      - run: wget http://phino.objectionary.com/releases/ubuntu-24.04/phino-latest -o /usr/bin/phino
      - uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ubuntu-jdk-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ubuntu-jdk-maven-
      - run: |
          set -x
          SECONDS=0
          make
      - run: |
          results=$(
            cat results.md
            printf "\nThe entire test took %d seconds.\n" "${SECONDS}"
          )
          export results
          perl -i -0777 -pe 's/(?<=<!-- benchmark_begin -->).*(?=<!-- benchmark_end -->)/\n$ENV{results}\n/gs;' README.md
          url=${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}
          export url
          perl -i -0777 -pe 's/(?<=\[benchmark-gha\]: ).*(?=\n)/$ENV{url}/gs;' README.md
        if: github.ref == 'refs/heads/master'
      - uses: peter-evans/create-pull-request@v7
        with:
          sign-commits: true
          branch: make
          commit-message: 'new benchmark results'
          delete-branch: true
          title: 'New results of benchmarking'
          assignees: yegor256
          base: master
        if: github.ref == 'refs/heads/master'
      - run: mv html gh-pages
        if: github.ref == 'refs/heads/master'
      - uses: JamesIves/github-pages-deploy-action@v4.7.3
        with:
          branch: gh-pages
          folder: gh-pages
          clean: false
        if: github.ref == 'refs/heads/master'
