# SPDX-FileCopyrightText: Copyright (c) 2023-2025 Objectionary.com
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: mvn
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  mvn:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 20
      - uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ubuntu-jdk-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ubuntu-jdk-maven-
      - run: mvn package
